spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: 3edc2wsx
    database: 0
    pool:
      max-active: 20
      max-idle: 20
      min-idle: 0
    sentinel:
      master: mymaster
      nodes: 192.168.56.107:26379,192.168.56.107:26380,192.168.56.107:26381
  http:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
s3:
  accessKey: *
  accessToken: *
  region: *
  bucket: *

redisson:
  master-name: mymaster
  password: 3edc2wsx
  sentinel-addresses: redis://192.168.56.107:26379, redis://192.168.56.107:26380, redis://192.168.56.107:26381